services:
  orderservice: &app
    build:
      context: .
      dockerfile: orderservice/docker/Dockerfile
    hostname: orderservice
    environment:
      SERVER_PORT: 8081
      DATABASE_URL: jdbc:postgresql://localhost:5432/ordermanagement_db
      DATABASE_USERNAME: fmass
      DATABASE_PASSWORD: lmi56n
      DB_POOL: 35
      CLUSTER: true
      CLUSTER_WORKERS: 5
    volumes:
      - ./:/app
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    depends_on:
      - db-postgresql
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '300M'
    network_mode: "host"

  paymentservice:
    build:
      context: .
      dockerfile: payment-service/docker/Dockerfile
    hostname: payment-service
    environment:
      SERVER_PORT: 8082
    volumes:
      - ./:/app
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    depends_on:
      - orderservice
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '300M'
    network_mode: "host"

  db-postgresql:
    image: 'postgres:latest'
    hostname: db-postgresql
    environment:
      - POSTGRES_DB=order_agibank_db
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
    ports:
      - '5432:5432'
    command: "postgres -c max_connections=400 -c shared_buffers=512MB -c effective_cache_size=1536MB -c maintenance_work_mem=256MB -c checkpoint_completion_target=0.9 -c wal_buffers=16MB -c default_statistics_target=100 -c random_page_cost=1.1 -c effective_io_concurrency=200 -c work_mem=1310kB -c huge_pages=off -c min_wal_size=1GB -c max_wal_size=4GB"
    network_mode: "host"